name: zlib-build
on:
  push:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'ABC'
        required: false
        default: 'false'
      
jobs:
  zlib-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: xyz
          
      - name: Checkout zlib
        run: |
          pwd
          ls
          git clone --depth 1 --branch v1.2.12 https://github.com/madler/zlib.git
          ls
        
      - name: Check Environment
        run: |
          export
          pwd
          whoami
          lsb_release -a
          uname -a
          uptime
          ls
          
      - name: Configure
        run: |
          pwd
          cd zlib
          ./configure
          
      - name: Compile
        run: |
          pwd
          cd zlib
          make
          
