name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: madler/zlib
          ref: v1.2.12
          path: zlib
        
      - name: Check Environment
        run: |
          lsb_release -a
          uname -a
          uptime
          pwd
          whoami
          ls
      - name: Configure
        run: |
          cd zlib
          ./configure
      - name: Compile
        run: |
          pwd
          make
          
